### ISSUE TITLE
Fix display layout when installing examples using command line buddy

### ISSUE THREAD

**Issue by jctophefabre** [OpenFLUID/openfluid#1001]
When running the command `openfluid buddy examples` for (re)installing examples, the displayed text is not correctly layouted. 
Screenshot below on Debian 10:

![examplesbuddy_textlayout](https://user-images.githubusercontent.com/3294350/106865750-e4537100-66cb-11eb-87ff-191c0934df6f.png)

**Comment by Arthoni** [comment]
- [x] Frame / Specs / Reference test
- [x] Implementation
- [ ] General testing / Validation / Cleaning
- [ ] Code review
