### ISSUE TITLE
In DevStudio, no error message at ware compilation if CMake is not found in the path

### ISSUE THREAD

**Issue by crevoisier** [OpenFLUID/openfluid#1031]
In DevStudio, if CMake is not found in the path, nothing append when button "configure" or "build" is pressed (behaviour observed in windows 10). The same behaviour is observed when passing through the development dashboard.

As this behaviour has been noticed on Windows system, it should be explored and confirmed for each OS.

**Comment by Arthoni** [comment]
## Windows
Bug confirmed on Windows system when CMake not installed or found.

## Ubuntu
Tried to replicate for Ubuntu 20.04 with Docker image without cmake: stops at dpkg time with error :
```
openfluid@90c57e32a7fe:/shared/test$ sudo dpkg -i openfluid_2.1.11_focal_amd64.deb 
Selecting previously unselected package openfluid.
(Reading database ... 226096 files and directories currently installed.)
Preparing to unpack openfluid_2.1.11_focal_amd64.deb ...
Unpacking openfluid (2.1.11) ...
dpkg: dependency problems prevent configuration of openfluid:
openfluid depends on cmake (>= 3.1); however:
	Package cmake is not installed.

dpkg: error processing package openfluid (--install):
dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Errors were encountered while processing:
openfluid
```
So unable to reproduce this precise error, but fix for windows case should work for all systems
