### ISSUE TITLE
Datasources file for generators is automatically deleted when saving current project

### ISSUE THREAD

**Issue by martin-faucher** [OpenFLUID/openfluid#1047]
When trying to setup a variable generator based on file injection in OpenFLUID-Builder, the .fluidx source file is deleted as soon as the project is saved. 
A solution is to store the file in a folder located in the input directory.

Content of the file :

```
<?xml version="1.0" standalone="yes"?>
<openfluid>
 
  <datasources>
    <filesource ID="1" file="datasource/water-soil-availability-irk.dat" />
    <filesource ID="2" file="datasource/water-soil-availability-vine.dat" />
    <filesource ID="3" file="datasource/atm-surf.ETP.dat" />
    <filesource ID="4" file="datasource/atm-surf.temperature.mean.dat" />
    <filesource ID="5" file="datasource/atm-surf.water.rain.dat" />     
  </datasources>
  
</openfluid>
```

**Comment by jctophefabre** [comment]
It seems that the problem is due to the `.fluidx` file extension used in this case, which is not correct as it is not a dataset descriptor file. `.xml`must be used instead.
The documentation should be upgraded to clarify this point.
