### ISSUE TITLE
Open wares tabs should be reopened in the same order

### ISSUE THREAD

**Issue by jctophefabre** [OpenFLUID/openfluid#1052]
When Devstudio quits, it stores the opened wares tabs in the workspace settings, in order to reopen them the next time.
Due to the usage of an ordered map to store the list of opened wares, wares paths are stored in alphabetical order and not in the wares tabs order.

**Comment by Arthoni** [comment]
I commited a proposal of resolution based on custom ordered map:
Several options:
- keep this proposal as is
- keep it but set the custom ordered map as utils class
- ignore this proposal to avoid new container definition, and instead do a quick replication of keys in a sorted container (vector) to keep the order somewhere (downside: redundancy of data)
