### ISSUE TITLE
Different default float format in output for csv observer between OpenFLUID versions

### ISSUE THREAD

**Issue by Arthoni** [OpenFLUID/openfluid#1063]
A basic csv observer can generate different outputs depending on the openfluid version before or after 2.1.10 (introduction of float format choice with change of default value: `default` instead of `fixed`)

## Example
Before: 
```#datetime;my.var
20210823T000000;0.00000
20210823T000500;0.01235
20210823T001000;0.01235
20210823T001500;0.01235
```
After:
```#datetime;my.var
20210823T000000;0
20210823T000500;0.01235
20210823T001000;0.01235
20210823T001500;0.01235
```
## Impact
Tests based on expected values may fail based on this difference of format, as reported by N.L.

## Mitigation
Revert default value to fixed ?
or notify this change in changelog notes or elsewhere ?

**Comment by jctophefabre** [comment]
A future [OpenFLUID blog](https://www.openfluid-project.org/blog/) article will be published to inform the users
