### ISSUE TITLE
Introduce ware board in DevStudio

### ISSUE THREAD

**Issue by jctophefabre** [OpenFLUID/openfluid#1127]
Introduce a ware board in OpenFLUID-DevStudio
* possible location : in a newly created tab widget, next to the Message location
* linked to the "check" procedure (see also `check`command : #1098 )
* may propose to migrate the wares sources if not formatted for OpenFLUID 2.2.0

**Comment by Arthoni** [comment]
Done in PR https://github.com/OpenFLUID/openfluid/pull/1139
