### ISSUE TITLE
Segmentation fault after throwing an exception for a required variable that is not produced

### ISSUE THREAD

**Issue by crevoisier** [OpenFLUID/openfluid#1141]
During checkConsistency stage, the simulation crashes with Segmentation fault.

Error followed by debug until the file src/openfluid/machine/Engine.cpp :
void Engine::checkConsistency()
{
...
catch (openfluid::base::FrameworkException& E)
  {
    mp_MachineListener->onCheckConsistencyDone(openfluid::machine::MachineListener::LISTEN_ERROR);
    // here, last debug info displayed at screen
    throw;
...

**Comment by jctophefabre** [comment]
* on Mac (Apple Silicon, macOS 13.3) : cannot be reproduced, missing variable is correctly handled with a managed error without crash

**Comment by jctophefabre** [comment]
@crevoisier Can we consider that this bug is invalid, maybe a side-effect due to external code?
