### ISSUE TITLE
debian 11 libgdal.so.30: cannot open shared object file

### ISSUE THREAD

**Issue by bonushenricus** [OpenFLUID/openfluid#1149]
Hello
I believe is a common error.
openfluid-builder: error while loading shared libraries: libgdal.so.30: cannot open shared object file: No such file or directory
How I can manage this.
Debian 11. openfluid_2.1.11_jammy_amd64.deb
(for the installation from the source I have a trouble with latex. Maybe I will write another Issue)
Thank you

**Comment by Arthoni** [comment]
Hello, about this gdal issue : make sure you installed every required package, for ubuntu :

Ifyou want minimal installation (which will lead to missing features) and only miss gdal, the packages are `libgdal-dev libgeos++-dev`


Extensive list of useful packages and more information are available on our community page: https://community.openfluid-project.org/start/install/


If you already installed the gdal libraries and still get this issue we will go through a deeper analysis.

**Comment by Arthoni** [comment]
Hello, 
OpenFLUID current releases up to 2.1.11 are not officially compatible with Debian 11.
However I did succeed to build it from source in a Docker image based on Debian 11 with the following packages (slightly different from the ones on our community page https://community.openfluid-project.org/coredev/build/):
```
apt-get update && \
  apt-get install -y build-essential g++ gfortran git cmake \
                     texlive-latex-extra texlive-fonts-extra latex2html doxygen pandoc pandoc-citeproc \
                     libboost-all-dev libgdal-dev libgeos++-dev rapidjson-dev \
                     qtchooser qt5-qmake qtbase5-dev qtbase5-dev-tools qttools5-dev qttools5-dev-tools libqt5svg5-dev \
                     p7zip-full gnuplot graphviz \
                     r-base-dev \
                     python3-setuptools \
                     mc nano bash-completion lsb-release sudo \
                     nodejs npm
```

And then I configured cmake as follows:
```
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
```

I built and installed it and was able to run an example project without any complaint about gdal:
```
openfluid run /usr/share/doc/openfluid/examples/projects/MHYDAS_Roujan/IN OUT
```

Did these steps helped you or does it fails somewhere?

**Comment by bonushenricus** [comment]
In Debian11 and 12 qt5-default is missing. It seems is mandatory.

**Comment by Arthoni** [comment]
Hello,
You are trying to install OpenFLUID using a package made for an other version of Debian, that will not work. 
For now, OpenFLUID has no official support for Debian 11, only 9 and 10.
You have three options:
- use an other OS or version for which a packaged version is available, or run it through a docker container (cf https://hub.docker.com/r/openfluid/openfluid)
- rebuild it from source using the package list I gave in my first comment (that does not contain qt5-default),
- wait until the release of OpenFLUID 2.2 that will support Debian 11 (but not in the next months)
