### ISSUE TITLE
installation from source: latex problem

### ISSUE THREAD

**Issue by bonushenricus** [OpenFLUID/openfluid#1150]
Hello
After
`cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
make -j 2`
give me this:

> [ 92%] Generating ../docbuild/latex/main.pdf
warning: Tag 'LATEX_SOURCE_CODE' at line 33 of file '/home/bonushenricus/Scaricati/openfluid_2.1.11_src/_build/doc/LaTeX-Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
[ 92%] Generating ../dist/share/doc/openfluid/main/openfluid_manual_2.1.11.pdf
Error copying file "/home/bonushenricus/Scaricati/openfluid_2.1.11_src/_build/docbuild/latex/main.pdf" to "/home/bonushenricus/Scaricati/openfluid_2.1.11_src/_build/dist/share/doc/openfluid/main/openfluid_manual_2.1.11.pdf".
gmake[2]: *** [doc/CMakeFiles/openfluid-doc-pdf.dir/build.make:73: dist/share/doc/openfluid/main/openfluid_manual_2.1.11.pdf] Errore 1
gmake[1]: *** [CMakeFiles/Makefile2:3580: doc/CMakeFiles/openfluid-doc-pdf.dir/all] Errore 2
gmake: *** [Makefile:156: all] Errore 2

I tried with
`doxygen -u /home/bonushenricus/Scaricati/openfluid_2.1.11_src/_build/doc/LaTeX-Doxyfile`
but the problem stays.

**With cmake, how I can exclude the pdf buil documentation?**

**Comment by jctophefabre** [comment]
Hello,

Assuming you are using the 2.1.11 version, you can add the `-DOFBUILD_ENABLE_DOCS=OFF` argument to the CMake command line, e.g.
```
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DOFBUILD_ENABLE_DOCS=OFF
```
Be sure to clean your build directory before running the cmake command, then rebuild OpenFLUID using make

**Comment by bonushenricus** [comment]
In Debian12 qt5-default is missing. It seems is mandatory.
