### ISSUE TITLE
DevStudio crashes when CMake cannot be found in PATH

### ISSUE THREAD

**Issue by polychloriert** [OpenFLUID/openfluid#661]
Hi,
in order to compile a (custom) simulator I installed OpenFLUID 2.1.0 (win32), cmake 3.4.3-win32, and qt 5.4.2-mingw491 as described in the wiki. Whenever I try to build a simulator project, e.g. from the MHYDAS model, the application crashes with a generic error message 
> This application has requested the Runtime to terminate it in an usual way. Please contact the support team.

Is there a way to fix this or at least narrow down the source of the problem? Thank you!
OS: Windows 7, 64 bit

[edit] clarification added, it crashes on an attempted build, not open

**Comment by fabrejc** [comment]
Hi,

In order to build simulators on Windows systems, DevStudio must be configured to find the installed build tools (MinGW). Have you set up this configuration? If not, you have to go to the _Edit>Preferences_ menu, then select _Development tools_ and click on _Detect Qt development tools_ button. It has to be done only once.

I also recommend you to download and install the latest version of OpenFLUID (2.1.1) as every new release fixes bugs.

Regards

**Comment by polychloriert** [comment]
Thanks for your reply. I updated to 2.1.1 and set the path to Qt but the application still crashes with the same message. As a side note: I guess, cmake has to be in the PATH variable as well?

**Comment by fabrejc** [comment]
Yes, CMake has to be in the PATH (at system level or configured in DevStudio)

**Comment by polychloriert** [comment]
Thanks, I added the path to cmake/bin but unfortunately this doesn't stop the crashes. Is there a way to get some debug output or something similar?

The Config PATH field in DevStudio now contains the following:
C:\Qt\5.4\mingw491_32\bin;C:\Qt\Tools\mingw491_32\bin;C:\Program Files (x86)\CMake\bin;%%PATH%%
CMake generator field: MinGW Makefiles
and the other fields are empty

**Comment by fabrejc** [comment]
I tried to reproduce the crash, but I cannot, it works for me. :(
In order to examine the environment variables, can you please post the output of a "set" command ran in a command prompt?
Thanks

**Comment by polychloriert** [comment]
> ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\foo\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
ComSpec=C:\windows\system32\cmd.exe
FavsDelTask=YES
FLEXLM_TIMEOUT=1000000
FP_NO_HOST_CHECK=NO
LOCALAPPDATA=C:\Users\foo\AppData\Local
LOGONSERVER=\\ADELEVDC009
NUMBER_OF_PROCESSORS=4
OPENFLUID_INSTALL_PREFIX=C:\Test\OpenFLUID-2.1.1
OS=Windows_NT
Path=C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\Program Files (x
86)\Microsoft Application Virtualization Client;C:\Program Files (x86)\Common Fi
les\Lenovo;C:\Program Files\Common Files\Lenovo;C:\Program Files (x86)\Lenovo\Cl
ient Security Solution;C:\Program Files\Lenovo\Client Security Solution;C:\Progr
am Files (x86)\Lotus\Notes;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Progra
m Files (x86)\QuickTime\QTSystem\;C:\Users\foo\.dnx\bin;C:\Program Files\Micro
soft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolk
it\;C:\Test\OpenFLUID-2.1.1\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PKG_CONFIG_PATH=C:\Test\OPENFL~1.1\lib\pkgconfig
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3c03
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\windows\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SWSHARE=C:\SWSHARE
SystemDrive=C:
SystemRoot=C:\windows
TEMP=C:\Users\foo\AppData\Local\Temp
TMP=C:\Users\foo\AppData\Local\Temp
VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
windir=C:\windows
windows_tracing_flags=3
windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log

I had to remove some entries but they shouldn't be relevant to the problem. HTH

**Comment by fabrejc** [comment]
OK, thanks for the informations.
The crash occurs when you click on the configure button or on the build button?

Can you try to put the CMake path in your system PATH env. var. and remove it from the OpenFLUID-DevStudio configuration? I suspect that the space in the CMake path may cause problems when set in the OpenFLUID-DevStudio configuration.

**Comment by fabrejc** [comment]
OK, I successfully reproduced the crash. It is caused by the missing CMake Path in the Path env. var. at system level. If you set it correctly, it should work.
In any case, I note this as a bug and I will fix it soon. Thanks a lot for having open this issue.

**Comment by polychloriert** [comment]
I changed the installation directory of cmake to something without spaces and adapted the PATH variable accordingly. Now the build process seems to work. Thank you! :)

**Comment by fabrejc** [comment]
Great!
