### ISSUE TITLE
Can not reference openfluid::tools in Simulator

### ISSUE THREAD

**Issue by polychloriert** [OpenFLUID/openfluid#662]
Hi there,
I tried to create a simulator within DevStudio which makes use of the OpenFLUID API/tools such as ColumnTextParser. Unfortunately, the simulator does not compile and cmake complains:

> undefined reference to `openfluid::tools::ColumnTextParser::ColumnTextParser(std::string const&, std::string const&)'

My first thought was that I did something wrong, so I tried to compile the test case tests/simulators/tests.tools as a simulator within DevStudio but this doesn't compile, as well.

My system setup is as before: Windows 7 64bit with cmake 3.4.3 mingw, openfluid 2.1.1, and qt 5.4.2 mingw.
Any ideas? Thanks!

**Comment by fabrejc** [comment]
Hi,

I think there is a missing link to the openfluid::tools components library.
In order to fix this problem, you have to edit your CMake.in.config file, and change the line
`SET(SIM_OPENFLUID_COMPONENTS )`
to
`SET(SIM_OPENFLUID_COMPONENTS tools)`
(It is around line 33 in the CMake.in.config file if you generated it automatically using DevStudio)

Hope it helps
Jean-Christophe

**Comment by polychloriert** [comment]
Thanks for your quick reply. I added the statement but DevStudio seems to reset the CMake.in.config file every time I start a build process. So the link always disappears and compilation aborts.

**Comment by fabrejc** [comment]
Can you please copy-paste your CMake.in.config file just after having edited the file?
Thanks

**Comment by polychloriert** [comment]
Here you go:
[CMake.in.config.txt](https://github.com/OpenFLUID/openfluid/files/142304/CMake.in.config.txt)

**Comment by fabrejc** [comment]
Thanks for the file.
I try to reproduce the problem and keep you informed.

**Comment by fabrejc** [comment]
Ok, I tried to reproduce your problem (my config: Win7+mingw, OpenFLUID 2.1.1), but it works for me.
Here are the source code and CMake config:
- [CMake.in.config](https://gist.github.com/fabrejc/03cfadceb89ac61b8c6c)
- [MySim.cpp](https://gist.github.com/fabrejc/50e8c50e623a844d4448)

I cannot reproduce the CMake.in.config reset problem you encountered. Can you make another try and verify that all files are correctly saved before launching the build process?
Thanks

**Comment by polychloriert** [comment]
Ah, I made an observation:
Previously I edited the .config with an editor outside of DevStudio. It seems that DevStudio was not aware of these changes and thus always reverted the changes. If the adaption is made from within DevStudio or is present when the program is started, the edit stays.
Nevertheless, DevStudio will neither compile my Simulator nor the test case and fails with the error message given above.

**Comment by fabrejc** [comment]
OK
If possible, can you send me the whole folder of the simulator source code? (as a zip file or other archive format)
I will try to build it "as-is" on my installation of OpenFLUID for Windows to find out where the problem comes from.

**Comment by polychloriert** [comment]
Ah, nevermind. All it needed was another Configure and then it worked well. Merci beaucoup :)

**Comment by fabrejc** [comment]
Great!
