### ISSUE TITLE
Add support of GDAL 2.x

### ISSUE THREAD

**Issue by cachambon** [OpenFLUID/openfluid#693]
On Fedora 23 and later, the configuration of the build of OpenFluid from sources fails with this error: 

> -- Found GDAL: /usr/lib64/libgdal.so
> CMake Error at /home/cachambon/git/openfluid_build_release/dist/lib64/openfluid/cmake/OpenFLUIDHelpersConfig.cmake:103 (MESSAGE):
>   OpenFLUID does not support GDAL v2.0.2.  Only versions 1.x are
>   currently supported

Since Fedora 23, only GDAL v2.x is available from official repositories.
It would be convenient to make OpenFluid support GDAL v2.x.

**Comment by fabrejc** [comment]
This has been fixed in commit [bd2e4b557cfec96076613284142ee08944a88f53](https://github.com/OpenFLUID/openfluid/commit/bd2e4b557cfec96076613284142ee08944a88f53)
See also closed issue #648
