### ISSUE TITLE
Export Geovector Shapefile - decimal values

### ISSUE THREAD

**Issue by TristanCereg** [OpenFLUID/openfluid#739]
I'm trying to export variables to shapefile on my Reach Segment units.
The output shapefile is generated but there's only "0" values as decimals while my variable is declared as Double.
The .csv export is ok and gives me this kind of result : 
#datetime;water.surf.QpRS.downstream-rs
2009/01/17 00:00:00;0.00000
2009/01/31 00:00:00;55.50324
The output shapefile displays "55.00000000"...

**Comment by fabrejc** [comment]
Hi!
I could not reproduce the problem.
Could you please send me by email the full project with GIS data that leads to the wrong values in the shapefiles?
Thanks

JC
