### ISSUE TITLE
Auto completion no longer works in DevStudio

### ISSUE THREAD

**Issue by chataignerm** [OpenFLUID/openfluid#740]

**Comment by fabrejc** [comment]
See if it is related to the Qt4 -> Qt5 switch

**Comment by fabrejc** [comment]
I have tested under various systems and Qt versions:
* Linux ubuntu trusty + Qt 5.2.1 : OK
* Linux debian jessie + Qt 5.3.2 : **Fail**
* Windows 8.1 + Qt 5.4.2 : OK
* Linux ubuntu xenial + Qt 5.5.1 : **Fail**
* Linux debian strecth + Qt 5.7.1 : OK
* Linux ubuntu artful + Qt 5.9.1 : OK
