### ISSUE TITLE
Add setAttributes/getAttributes functions for batch processing in ROpenFLUID

### ISSUE THREAD

**Issue by fabrejc** [OpenFLUID/openfluid#765]

**Comment by crevoisier** [comment]
batch set/getAttribute functions in the functions set/getAttributes
- getAttributes get a simulation definition blob, an unit class name, a vector of unit id, a vector of attribute names and returns a data.frame, unit id by row and attribute name by column (an optional unitid column in the returned data.frame can be added)
- setAttributes get a simulation definition blob, an unit class name and a data.frame (with or without optional column)
