### ISSUE TITLE
CMake error with Doxygen on Ubuntu 18.04

### ISSUE THREAD

**Issue by fabrejc** [OpenFLUID/openfluid#778]
Error message:
```
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found
components:  doxygen dot error: Cannot open
file /home/xlouchart/Téléchargements/OF_2.1.5/openfluid_2.1.5_src/_build/CMakeDoxyfile.tpl
for writing CMake Error
at /usr/share/cmake-3.10/Modules/FindDoxygen.cmake:630 (message):
Unable to generate Doxyfile template: 1 Call Stack (most recent call
first): CMakeLists.txt:113 (FIND_PACKAGE)
```

**Comment by phanousk** [comment]
I confirm the error:
`-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen dot 
error: Cannot open file /home/hanousek/Stažené/cesnet/linphone/20180625/06-linphone/ph/CMakeDoxyfile.tpl for writing
CMake Error at /usr/share/cmake-3.11/Modules/FindDoxygen.cmake:665 (message):
  Unable to generate Doxyfile template: 1
Call Stack (most recent call first):
  coreapi/help/doc/doxygen/CMakeLists.txt:24 (find_package)`

Linphone version:
`git describe --tags
3.12.0-355-gbb8c1866b`

System: Debian testing/unstable

**Comment by fabrejc** [comment]
OpenFLUID is independent from Linphone, so the bug seems to be related to the CMake module for Doxygen, or maybe to Doxygen itself.
Thank you very much for your contribution :+1:
