### ISSUE TITLE
Connection to wareshub instance does not work sometimes

### ISSUE THREAD

**Issue by fabrejc** [OpenFLUID/openfluid#908]
Investigate why.

**Comment by Arthoni** [comment]
_On linux setup with internet (not in LAN), version 2.1.9_
Works with:
- https://dev.openfluid-project.org/lisah-wareshub/api
- https://dev.openfluid-project.org/lisah-wareshub/api/

Does not work with:
- https://dev.openfluid-project.org/lisah-wareshub/

SSL check deactivation does not affect results.
