### ISSUE TITLE
Changing simulation end time not updated when running in command line mode

### ISSUE THREAD

**Issue by eup31000** [OpenFLUID/openfluid#969]
After changing the simulation end time on 'Simulation Configuration' tab and rerunning the model in Builder under command line mode, the log window still shows the former simulation end time. In screenshot new end time is 12:00, but log shows former end time 16:00. Results files are fine as is running in normal mode.
OpenFluid-Builder version 2.1.10
![ofLog12h00](https://user-images.githubusercontent.com/47326765/92083611-935eea00-edc6-11ea-8607-c7ff19535140.png)

**Comment by fabrejc** [comment]
I have also noticed strange behaviour using this run mode. I suspect that is coming from a failing write of the project on disk, only in this specific run mode.
I will investigate to confirm the bug.

**Comment by fabrejc** [comment]
The problem occurs after a "Save As..." of the project, probably due to a wrong update of the project path. 

(Status changed to confirmed bug, problem must be investigated)
