### ISSUE TITLE
DeltaT checked mode for simulator returning Never() in initializeRun()

### ISSUE THREAD

**Issue by eup31000** [OpenFLUID/openfluid#987]
I have an OpenFluid project with 2 simulators:
-training.spatial.scale: this is a 1 time run simulator used to clone the spatial domain in prepareData() (that I use internally to di scalability/performance tests). The simulator returns Never() from initializeRun() as it does not need to be called anymore once it has cloned the spatial domain according to its input parameter
-water.surface.irrig-su.opti: this a simulator that calls the daily Optirig pilote() function for irrigation optimization. Since pilote() function performs daily calculation, it returns 1 day in seconds (openfluid::base::SchedulingRequest(24*3600)) from runStep() and initializeRun()

With the above setup, OpenFluid gives an error at time 0 about deltaT mode in 1st simulator not compatible with the 2nd simulator deltaT mode :

![image](https://user-images.githubusercontent.com/47326765/96422536-7193b800-11f8-11eb-8d35-f3d31faef234.png)
Since the first simulator is used only at time 0 and is never called for time-stepping, I believe that the framework should not enforce the deltaT mode requirement to the 1st simulator.

**Comment by jctophefabre** [comment]
Thank you @eup31000 for mentioning this problem.
Can you paste a copy of the signature of the simulator in this discussion? Thanks

**Comment by eup31000** [comment]
Actually, I think that the problem is only with the initializeRun() function return value:
-in the first simulator, initializeRun() signature is "return Never();"
-in the second simulator, initializeRun() signature is "return openfluid::base::SchedulingRequest(24*3600);"
When using "return DefaultDeltaT();" for the 2nd simulator, the current code works

**Comment by jctophefabre** [comment]
When I asked for the signature, I meant the code between `BEGIN_SIMULATOR_SIGNATURE` and `END_SIMULATOR_SIGNATURE` usually located at the beginning of the main .cpp file of the simulator.
Can you paste it in the discussion? Thanks

**Comment by eup31000** [comment]
Sorry for the misunderstanding ...
### **For the 1st simulator (with no time-stepping):**
BEGIN_SIMULATOR_SIGNATURE("training.spatial.scale")

  // Informations
  DECLARE_NAME("")
  DECLARE_DESCRIPTION("One time startup run simulator to duplicate spatial domain by scale parameter")
  DECLARE_VERSION("")
  DECLARE_STATUS(openfluid::ware::EXPERIMENTAL)
  DECLARE_AUTHOR("Alain Dupuy","alain.dupuy@inrae.fr")
  
  DECLARE_UPDATED_UNITSGRAPH("Scaling of spatial graph for profiling ...")
  DECLARE_UPDATED_UNITSCLASS("SU","")
  DECLARE_UPDATED_UNITSCLASS("RS","")  
  DECLARE_USED_PARAMETER("geoscale","Scale factor for spatial domain","")

END_SIMULATOR_SIGNATURE

**### For the 2nd simulator (with time-step of 1 day):**

BEGIN_SIMULATOR_SIGNATURE("water.surface.irrig-su.opti")

  // Informations
  DECLARE_NAME("Optimisation irrigation par appel a fonction pilote du simulateur R Optirig")
  DECLARE_DESCRIPTION("")
  DECLARE_VERSION("")
  DECLARE_STATUS(openfluid::ware::EXPERIMENTAL)
  DECLARE_DOMAIN("irrigation");
  DECLARE_AUTHOR("Alain Dupuy","alain.dupuy@inrae.fr");

  //Optirig files
  DECLARE_REQUIRED_PARAMETER("param_file","Optirig global input parameters","")
  DECLARE_REQUIRED_EXTRAFILE("param_EE.csv")
  DECLARE_REQUIRED_EXTRAFILE("irrigmaker.txt")  
  
  //Optirig parameters specified at SU level
  DECLARE_USED_ATTRIBUTE("tetawp","SU","Point de fletrissement","");
  
  DECLARE_PRODUCED_VARIABLE("water.surf.RU1max","SU","Max. réserve utile eau dans le réservoir R1","mm");  
  DECLARE_PRODUCED_VARIABLE("water.surf.R1P","SU","Eau de pluie dans le réservoir R1","mm");    
  DECLARE_PRODUCED_VARIABLE("water.surf.EL1P","SU","Eau de pluie liée dans le réservoir R1","mm");    
  DECLARE_PRODUCED_VARIABLE("water.surf.R1I","SU","Eau irriguée réservoir R1","mm");    
  DECLARE_PRODUCED_VARIABLE("water.surf.EL1I","SU","Eau irrigation liée dans le réservoir R1","mm");          
  DECLARE_PRODUCED_VARIABLE("water.surf.RU2max","SU","Max. réserve utile eau dans le réservoir R2","mm");    
  DECLARE_PRODUCED_VARIABLE("water.surf.R2P","SU","Eau de pluie dans le réservoir R2","mm");    
  DECLARE_PRODUCED_VARIABLE("water.surf.EL2P","SU","Eau de pluie liée dans le réservoir R2","mm");    
  DECLARE_PRODUCED_VARIABLE("water.surf.R2I","SU","Eau irriguée réservoir R2","mm");    
  DECLARE_PRODUCED_VARIABLE("water.surf.EL2I","SU","Eau irrigation liée dans le réservoir R2","mm");          
  
END_SIMULATOR_SIGNATURE

**Comment by jctophefabre** [comment]
Thanks! I would like to check if no coupling constraint was set to find out if there is a side effect tied to it

**Comment by eup31000** [comment]
Just let me know if you need the project & source code for the 2 simulators

**Comment by eup31000** [comment]
As follow-up after discussion, issue only happens if constraint under 'planification de simulation' is set to Vérifiée/Verified.
When set to Aucune/None, the simulation runs fine.
![image](https://user-images.githubusercontent.com/47326765/97580864-28134c00-19f4-11eb-96d2-dcafce58b831.png)

**Comment by jctophefabre** [comment]
So, it is the expected behaviour. I am closing the issue
