### ISSUE TITLE
Exception/bad allocation error when removing SUs from project with GNUplotObserver

### ISSUE THREAD

**Issue by eup31000** [OpenFLUID/openfluid#997]
After cloning an existing project with multiple SUs/RUs that also uses the exports.vars.plot.gnuplot observer (for instance TP3 project from training), I deleted all SUs and RUs except for number 1. After that, if I launch the simulation again, it runs but terminates with an error:
![image](https://user-images.githubusercontent.com/47326765/104597049-1fd2c080-5675-11eb-897f-b23c6a68c3ab.png)
After reproducing the error under VS code, the error appears to be in GNUplotObserver::onFinalizedRun().
It is clearly caused by user bad input data, but it would be nice to flag that in the observer with a proper error message rather than getting a generic error message (hard to understand what happened).
I can provide the TP3 project to reproduce the issue if needed. Also note that if the gnuplot observer parameters are edited under monitoring, then it seems that the observer self corrects and simulation runs fine ... However if I do not edit the observer after deleting the spatial units and save/close/open the project, the error is still there. I can reporduce the issue for 2.1.10 and 2.1.11

**Comment by Arthoni** [comment]
Reproduced with Firespread, by deleting last RS (used in the project gnuplot observer). End of simulation generates the same bad_alloc error message and "failed" status.
